### ISSUE TITLE
Possible bug: socket might have gotten closed before trying to send data

### ISSUE THREAD

**Issue by isaacdd** [DataDog/dogstatsd-python#20]
```
Aug  4 10:00:01 app01 host: [2014-08-04 10:00:00,007: INFO/MainProcess] Scheduler: Sending due task process_delayed_queue (flow.tasks.process_delayed_queue.process_delayed_queue)
Aug  4 10:00:01 app01 host: [2014-08-04 10:00:00,008: ERROR/MainProcess] Error submitting metric
Aug  4 10:00:01 app01 host: Traceback (most recent call last):
Aug  4 10:00:01 app01 host:  File "/usr/local/lib/python2.7/dist-packages/statsd.py", line 178, in _send_to_server
Aug  4 10:00:01 app01 host:    self.socket.send(packet.encode(self.encoding))
Aug  4 10:00:01 app01 host: error: [Errno 9] Bad file descriptor
Aug  4 10:00:01 app01 host: [2014-08-04 10:00:00,009: ERROR/MainProcess] Error submitting metric
Aug  4 10:00:01 app01 host: Traceback (most recent call last):
Aug  4 10:00:01 app01 host:  File "/usr/local/lib/python2.7/dist-packages/statsd.py", line 178, in _send_to_server
Aug  4 10:00:01 app01 host:    self.socket.send(packet.encode(self.encoding))
Aug  4 10:00:01 app01 host: error: [Errno 9] Bad file descriptor
```

**Comment by yannmh** [comment]
Closing, issue seemed correctly solved by #21. Thanks @bunelr
